[tool.poetry]
name = "sdne-lightning"
version = "0.1.0"
description = ""
authors = ["Kenya Nonaka"]
readme = "README.md"
packages = [{include = "sdne_lightning"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
